title: <p align="center">Светлана Кочмина</p> # name (website title) 
logo: "/images/logo.png?raw=true" # photo 
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="pdf/resume_kochmina_svetlana.pdf">Резюме</a> |
  <a href="https://github.com/ko-svetlana">GitHub</a>
  </p>
  
  <p align="justify">
  Аналитик данных. Специализации: продуктовая аналитика • BI аналитика • финансовая аналитика
  <br><br>
  Нахожу и предлагаю эффективные решения, соответствующие потребностям бизнеса, в четко обозначенные сроки. Умею коммуницировать с бизнес-командами, выявлять требования, презентовать результаты.
  <br><br>
  </p>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

