title: <p align="center">Светлана Кочмина</p> # name (website title) 
logo: "/images/logo.png?raw=true" # photo 
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="pdf/resume_kochmina_svetlana.pdf" target="_blank">Резюме</a> |
  <a href="https://github.com/ko-svetlana">GitHub</a> |
  <a href="https://t.me/KoSvetlana">Telegram</a>
  </p>
  
  <p align="center">
  <b>АНАЛИТИК</b>
  </p>
  
  <p>
  • Изучаю продуктовую аналитику и BI<br>
  • Имею опыт анализа рынков, конкурентов, финансового анализа
  </p>
  

  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

