title: <p align="center">Светлана Кочмина</p> # name (website title) 
logo: "/images/logo.png?raw=true" # photo 
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="pdf/resume_kochmina_svetlana.pdf">Резюме</a> |
  <a href="https://github.com/ko-svetlana">GitHub</a>
  </p>
  
  <p align="center">
  <b>АНАЛИТИК</b>
  </p>
  <p>
  • Работаю в исследовательском агентстве. <br>• Имею опыт анализа рынков, конкурентов, финансового анализа. <br>• Изучаю продуктовую аналитику и BI-системы
  </p>
  
  <ul>
  <li>Работаю в исследовательском агентстве</li>
  <li>Имею опыт анализа рынков, конкурентов, финансового анализа</li>
  <li>Изучаю продуктовую аналитику и BI-системы</li>
  </ul>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

